import { TCandidate } from '@/types/pages/candidates/candidate'

const candidates: TCandidate[] = [
    {
        id: 1,
        first_name: 'John',
        last_name: 'Doe',
        age: 29,
        email: 'john.doe@example.com',
        phone: '123-456-7890',
        unit: 'New York',
        status: 0,
        interview_date: new Date('2024-10-15'),
        enrollment_date: new Date('2024-11-01'),
        created_date: new Date('2024-09-01'),
        profile_img_url: 'https://picsum.photos/200/300?random=1',
        files: [
            {
                id: 1,
                name: 'Resume.pdf',
                uri: '/files/resume1.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 101,
    },
    {
        id: 2,
        first_name: 'Jane',
        last_name: 'Smith',
        age: 32,
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        unit: 'Los Angeles',
        status: 1,
        interview_date: new Date('2024-10-20'),
        enrollment_date: new Date('2024-11-10'),
        created_date: new Date('2024-09-05'),
        profile_img_url: 'https://picsum.photos/200/300?random=2',
        files: [
            {
                id: 2,
                name: 'Portfolio.pdf',
                uri: '/files/portfolio2.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 102,
    },
    {
        id: 3,
        first_name: 'Carlos',
        last_name: 'Lopez',
        age: 27,
        email: 'carlos.lopez@example.com',
        phone: '555-123-4567',
        unit: 'Chicago',
        status: 2,
        interview_date: new Date('2024-09-10'),
        enrollment_date: new Date('2024-09-30'),
        created_date: new Date('2024-08-15'),
        profile_img_url: 'https://picsum.photos/200/300?random=3',
        files: [
            {
                id: 3,
                name: 'CoverLetter.docx',
                uri: '/files/cover3.docx',
                type: 'docx',
            },
        ],
        conversation_id: 103,
    },
    {
        id: 4,
        first_name: 'Emily',
        last_name: 'Davis',
        age: 30,
        email: 'emily.davis@example.com',
        phone: '444-789-1230',
        unit: 'Houston',
        status: 1,
        interview_date: new Date('2024-10-18'),
        enrollment_date: new Date('2024-11-05'),
        created_date: new Date('2024-09-12'),
        profile_img_url: 'https://picsum.photos/200/300?random=4',
        files: [
            {
                id: 4,
                name: 'Certificate.jpg',
                uri: '/files/cert4.jpg',
                type: 'jpg',
            },
        ],
        conversation_id: 104,
    },
    {
        id: 5,
        first_name: 'Daniel',
        last_name: 'Brown',
        age: 35,
        email: 'daniel.brown@example.com',
        phone: '123-555-7890',
        unit: 'Phoenix',
        status: 0,
        interview_date: new Date('2024-10-22'),
        enrollment_date: new Date('2024-11-15'),
        created_date: new Date('2024-09-20'),
        profile_img_url: 'https://picsum.photos/200/300?random=5',
        files: [
            {
                id: 5,
                name: 'Transcript.pdf',
                uri: '/files/transcript5.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 105,
    },
    {
        id: 6,
        first_name: 'Sophia',
        last_name: 'Wilson',
        age: 26,
        email: 'sophia.wilson@example.com',
        phone: '456-789-1234',
        unit: 'Philadelphia',
        status: 2,
        interview_date: new Date('2024-08-22'),
        enrollment_date: new Date('2024-09-05'),
        created_date: new Date('2024-08-01'),
        profile_img_url: 'https://picsum.photos/200/300?random=6',
        files: [
            {
                id: 6,
                name: 'Presentation.pptx',
                uri: '/files/presentation6.pptx',
                type: 'pptx',
            },
        ],
        conversation_id: 106,
    },
    {
        id: 7,
        first_name: 'Michael',
        last_name: 'Clark',
        age: 31,
        email: 'michael.clark@example.com',
        phone: '789-123-4567',
        unit: 'San Diego',
        status: 0,
        interview_date: new Date('2024-10-17'),
        enrollment_date: new Date('2024-11-01'),
        created_date: new Date('2024-09-10'),
        profile_img_url: 'https://picsum.photos/200/300?random=7',
        files: [
            {
                id: 7,
                name: 'ReferenceLetter.pdf',
                uri: '/files/reference7.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 107,
    },
    {
        id: 8,
        first_name: 'Olivia',
        last_name: 'Martinez',
        age: 28,
        email: 'olivia.martinez@example.com',
        phone: '654-321-9870',
        unit: 'Dallas',
        status: 1,
        interview_date: new Date('2024-10-21'),
        enrollment_date: new Date('2024-11-10'),
        created_date: new Date('2024-09-07'),
        profile_img_url: 'https://picsum.photos/200/300?random=8',
        files: [
            {
                id: 8,
                name: 'IDProof.pdf',
                uri: '/files/idproof8.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 108,
    },
    {
        id: 9,
        first_name: 'Liam',
        last_name: 'Garcia',
        age: 33,
        email: 'liam.garcia@example.com',
        phone: '321-987-6540',
        unit: 'San Antonio',
        status: 2,
        interview_date: new Date('2024-09-15'),
        enrollment_date: new Date('2024-09-30'),
        created_date: new Date('2024-08-25'),
        profile_img_url: 'https://picsum.photos/200/300?random=9',
        files: [
            {
                id: 9,
                name: 'Diploma.pdf',
                uri: '/files/diploma9.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 109,
    },
    {
        id: 10,
        first_name: 'Emma',
        last_name: 'Taylor',
        age: 25,
        email: 'emma.taylor@example.com',
        phone: '111-222-3333',
        unit: 'Austin',
        status: 1,
        interview_date: new Date('2024-10-23'),
        enrollment_date: new Date('2024-11-20'),
        created_date: new Date('2024-09-15'),
        profile_img_url: 'https://picsum.photos/200/300?random=10',
        files: [
            {
                id: 10,
                name: 'Recommendation.pdf',
                uri: '/files/recommendation10.pdf',
                type: 'pdf',
            },
        ],
        conversation_id: 110,
    },
]

export default candidates
